package commun;

/**
 * commun/_CORBA_InterfaceStub.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from CORBA_Interface.idl domingo 10 de abril de
 * 2016 03:55:12 PM CDT
 */
public class _CORBA_InterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements commun.CORBA_Interface {

    public String sayHello() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("sayHello", true);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return sayHello();
        } finally {
            _releaseReply($in);
        }
    } // sayHello

    public String selectAll() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("selectAll", true);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return selectAll();
        } finally {
            _releaseReply($in);
        }
    } // selectAll

    public String insertRow(String ibt, String name, String lugar, String datetime) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("insertRow", true);
            $out.write_string(ibt);
            $out.write_string(name);
            $out.write_string(lugar);
            $out.write_string(datetime);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return insertRow(ibt, name, lugar, datetime);
        } finally {
            _releaseReply($in);
        }
    } // insertRow

    public String updateRow(String ibt, String lugar, String datetime) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("updateRow", true);
            $out.write_string(ibt);
            $out.write_string(lugar);
            $out.write_string(datetime);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return updateRow(ibt, lugar, datetime);
        } finally {
            _releaseReply($in);
        }
    } // updateRow

    public boolean isEmpty() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("isEmpty", true);
            $in = _invoke($out);
            boolean $result = $in.read_boolean();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return isEmpty();
        } finally {
            _releaseReply($in);
        }
    } // isEmpty

    public void recoveryBD(String ibt, String name, String lugar, String datetime) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("recoveryBD", true);
            $out.write_string(ibt);
            $out.write_string(name);
            $out.write_string(lugar);
            $out.write_string(datetime);
            $in = _invoke($out);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            recoveryBD(ibt, name, lugar, datetime);
        } finally {
            _releaseReply($in);
        }
    } // recoveryBD

    public void giveMeYourBD() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("giveMeYourBD", true);
            $in = _invoke($out);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            giveMeYourBD();
        } finally {
            _releaseReply($in);
        }
    } // giveMeYourBD

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:commun/CORBA_Interface:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            org.omg.CORBA.Object obj = orb.string_to_object(str);
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            _set_delegate(delegate);
        } finally {
            orb.destroy();
        }
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            String str = orb.object_to_string(this);
            s.writeUTF(str);
        } finally {
            orb.destroy();
        }
    }
} // class _CORBA_InterfaceStub
