package commun;


/**
* commun/CORBA_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_Interface.idl
* lunes 11 de abril de 2016 10:53:04 AM CDT
*/

public interface CORBA_InterfaceOperations 
{
  String sayHello ();
  String selectAll ();
  String insertRow (String ibt, String name, String lugar, String datetime, String password);
  String updateRow (String ibt, String lugar, String datetime, String password);
  boolean isEmpty ();
  void recoveryBD (String ibt, String name, String lugar, String datetime, String password);
  void giveMeYourBD ();
} // interface CORBA_InterfaceOperations
