package commun;


/**
* commun/CORBA_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_Interface.idl
* sábado 9 de abril de 2016 01:22:44 AM CDT
*/

public interface CORBA_InterfaceOperations 
{
  String sayHello ();
  String selectAll ();
  String insertRow ();
  String updateRow ();
  boolean isEmpty ();
} // interface CORBA_InterfaceOperations
