package commun;


/**
* commun/CORBA_InterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_Interface.idl
* sábado 9 de abril de 2016 01:22:44 AM CDT
*/

public abstract class CORBA_InterfacePOA extends org.omg.PortableServer.Servant
 implements commun.CORBA_InterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("selectAll", new java.lang.Integer (1));
    _methods.put ("insertRow", new java.lang.Integer (2));
    _methods.put ("updateRow", new java.lang.Integer (3));
    _methods.put ("isEmpty", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // commun/CORBA_Interface/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // commun/CORBA_Interface/selectAll
       {
         String $result = null;
         $result = this.selectAll ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // commun/CORBA_Interface/insertRow
       {
         String $result = null;
         $result = this.insertRow ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // commun/CORBA_Interface/updateRow
       {
         String $result = null;
         $result = this.updateRow ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // commun/CORBA_Interface/isEmpty
       {
         boolean $result = false;
         $result = this.isEmpty ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:commun/CORBA_Interface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CORBA_Interface _this() 
  {
    return CORBA_InterfaceHelper.narrow(
    super._this_object());
  }

  public CORBA_Interface _this(org.omg.CORBA.ORB orb) 
  {
    return CORBA_InterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CORBA_InterfacePOA
