package commun;


/**
* commun/CORBA_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_Interface.idl
* sábado 9 de abril de 2016 01:22:44 AM CDT
*/

public interface CORBA_Interface extends CORBA_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBA_Interface
