package commun;


/**
* commun/CORBA_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_Interface.idl
* domingo 10 de abril de 2016 03:55:12 PM CDT
*/

public interface CORBA_Interface extends CORBA_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBA_Interface
